[package]
name = "zesh"
version = "0.1.0"
description = "A tmux session manager"
authors = ["theoboldalex <theoboldalex@gmail.com>"]
license = "MIT"
edition = "2024"

[dependencies]
color-eyre = "0.6.3"
crossterm = "0.29.0"
ratatui = "0.29.0"
